### PR TITLE
Fix ios contact number fetch

### PR DESCRIPTION
**Pull request by vladyslavsosiuk**
This pull request fixes issue:
https://github.com/enisn/Xamarin.Forms.Contacts/issues/8

### CODE REVIEW

**Comment by Lunster** [comment]
Hey, good Job.  Is there any workaround for the current version until this gets released?

**Comment by vladyslavsosiuk** [comment]
Actually no, I just copied source code of current version for ios(notice that current source code in master is not finished, make sure tot take sc for last ver), replaced one line, and use it as dependency service. For android simply injected his implementation to his interface with dependency service

**Comment by enisn** [comment]
NuGet Package will be updated too,

**Comment by Lunster** [comment]
As of today the Nuget package still doesn't contain this change.

**Comment by DiogoMartinh0** [comment]
> As of today the Nuget package still doesn't contain this change.

Same, can we get an update soon?

**Comment by uysuy** [comment]
should release to Nuget package, I really need that fix for iOS.

Thanks in advance.

**Pull request merged**
